truncate table branch_attendance;
truncate table branch_courses;
truncate table classroom_attendance;
truncate table classroom_courses;
truncate table classrooms;
truncate table courses;
truncate table meetings;
truncate table students;
truncate table teachers;
truncate table users;
insert into users values ('root', 'toor', 1);
insert into users values ('sinifogr', '123456', 2);
insert into users values ('bransogr', '123456', 3);